export const PRODUCT_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCTS_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCTS_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCTS_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCTS_DETAILS_FAIL'
